name: drunk2025
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - flask
  - python-dotenv
  - pillow
  - efficientnet_pytorch
  - torch
  - torchvision
  - opencv-python
  - pymysql