name: drunk2025
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - flask
  - sqlalchemy
  - flask_sqlalchemy
  - python-dotenv
  - pillow
  - efficientnet_pytorch
  - torch
  - torchvision
  - opencv-python
  - pymysql
  - mysql-connector-python
  - face_recognition # 기존 haar 대신사용
  - reverse_geocoder # 좌표를 주소로 바꿔주는 모듈